version: '3'
services:
  infrastructure:
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    image: marcelocorreia/terraform
    volumes:
      - ./:/scripts
    entrypoint: /scripts/provisionInfrastructure.sh